# Generated by Django 5.2 on 2025-05-04 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('publicationDate', models.DateField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='papers/')),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('coauthor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('coauthor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('visibility', models.CharField(default='pending', max_length=20)),
                ('categories', models.ManyToManyField(blank=True, to='papers.category')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
