# Generated by Django 5.2 on 2025-05-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='coverImage',
            field=models.ImageField(blank=True, default='fallback_cover.png', null=True, upload_to='cover_images/'),
        ),
    ]
