name: 🚀 Deploy Django Backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'     # Include backend changes
      - '.github/workflows/deploy-backend.yml' 
      - '!frontend/**'    # Exclude frontend changes from triggering this workflow   

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      RDS_HOST:     ${{ secrets.RDS_HOST }}
      RDS_NAME:     ${{ secrets.RDS_NAME }}
      RDS_USER:     ${{ secrets.RDS_USER }}
      RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
      RDS_PORT:     ${{ secrets.RDS_PORT }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          printf "%s\n" "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Sync backend to EC2
        run: |
          rsync -avz \
            -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p ${{ secrets.EC2_PORT }}" \
            --exclude='venv/' \
            --exclude='.git/' \
            --exclude='frontend/' \
            backend/ ubuntu@${{ secrets.EC2_HOST }}:~/app/

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/id_rsa \
            -p ${{ secrets.EC2_PORT }} \
            ubuntu@${{ secrets.EC2_HOST }} << 'DEPLOY'
            set -e
            cd ~/app

            export RDS_HOST="${{ secrets.RDS_HOST }}"
            export RDS_NAME="${{ secrets.RDS_NAME }}"
            export RDS_USER="${{ secrets.RDS_USER }}"
            export RDS_PASSWORD="${{ secrets.RDS_PASSWORD }}"
            export RDS_PORT="${{ secrets.RDS_PORT }}"

            # Ensure venv support & recreate venv
            sudo apt-get update
            sudo apt-get install -y python3-venv python3-pip
            python3 -m venv --clear venv
            source venv/bin/activate

            # *** Install Nginx if it’s missing ***
            sudo apt-get install -y nginx

            # Install dependencies
            pip install --upgrade pip
            pip install -r requirements.txt

            # Django setup
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput

            # Restart services
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            DEPLOY

      - name: Verify deployment
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_rsa \
              -p ${{ secrets.EC2_PORT }} \
              ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            curl -sf http://localhost:8000/health-check/ \
            || { echo 'Django failed to start'; exit 1; }
            EOF