name: 🚀 Deploy Django Backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**' # Include backend changes
      - '.github/workflows/deploy-backend.yml'
      - '!frontend/**' # Exclude frontend changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DB_HOST:     ${{ secrets.RDS_HOST }}
      DB_NAME:     ${{ secrets.RDS_NAME }}
      DB_USER:     ${{ secrets.RDS_USER }}
      DB_PASSWORD: ${{ secrets.RDS_PASSWORD }}
      DB_PORT:     ${{ secrets.RDS_PORT }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH
        run: |
            # Create .ssh directory with strict permissions
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            
            # Write key using heredoc to preserve formatting
            cat << 'EOF' > ~/.ssh/id_rsa
            ${{ secrets.EC2_SSH_PRIVATE_KEY }}
            EOF
            
            # Set strict key permissions
            chmod 600 ~/.ssh/id_rsa
            
            # Verify key was written correctly
            ls -la ~/.ssh/
            head -n 3 ~/.ssh/id_rsa
            
            # Add host to known_hosts
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts 2>/dev/null

      - name: Validate SSH configuration
        run: |
            echo "SSH directory contents:"
            ls -la ~/.ssh/
            
            echo "First 3 lines of key:"
            head -n 3 ~/.ssh/id_rsa
            
            echo "Testing connection..."
            ssh -i ~/.ssh/id_rsa \
                -o StrictHostKeyChecking=no \
                -p ${{ secrets.EC2_PORT }} \
                ubuntu@${{ secrets.EC2_HOST }} \
                "echo 'SSH connection successful!'"

      - name: Validate connection
        run: |
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.EC2_PORT }} \
            ubuntu@${{ secrets.EC2_HOST }} "echo 'SSH successful'"

      - name: Sync code
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.EC2_PORT }}" \
            --exclude={'venv/','.git/','frontend/'} \
            ./ ubuntu@${{ secrets.EC2_HOST }}:~/app/

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.EC2_PORT }} ubuntu@${{ secrets.EC2_HOST }} << 'DEPLOY'
          set -e
          cd ~/app
          
          # Python setup
          if ! [ -d venv ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          pip install -r requirements.txt

          # Django
          python manage.py migrate
          python manage.py collectstatic --noinput

          # Services
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
          DEPLOY