name: Deploy Frontend to S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for AWS credentials

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend/paperpulse-frontend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Build frontend
        working-directory: frontend/paperpulse-frontend
        run: npm run build -- --configuration production

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions-Deploy

      - name: Verify build output
        run: ls -R frontend/paperpulse-frontend/dist/

      - name: Deploy to S3
        run: |
          aws s3 sync frontend/paperpulse-frontend/dist/paperpulse-frontend/browser \
            s3://${{ secrets.AWS_S3_BUCKET }} \
            --delete \
            --cache-control "max-age=31536000,public"